node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
       sh 'npm install --only=dev'
       sh 'npm test'
    }
 //**  stage('docker build/push') {
  //   docker.withRegistry('https://us.gcr.io', 'gcr:[sample-test-gcp-project]') {
    //   def app = docker.build("moregane/ganeshmore:${commit_id}", '.').push()
    // }
   //}
   stage('Build image') {
  app = docker.build("sample-test-gcp-project/node")
}
stage('Push image') {
  docker.withRegistry('https://eu.gcr.io', 'gcr:sample-test-gcp-project') {
    app.push("${env.BUILD_NUMBER}")
    app.push("latest")
  }
}
}
